kind: pipeline
type: docker
name: default

# workspace:
#   path: /var/www/html/

steps:

- name: build
  image: bitnami/laravel:latest
  pull: if-not-exists
  commands:
  - php --version
  - composer --version
  - composer install
  - php artisan --version
  - cp .env.example .env
  - php artisan key:generate
  - sleep 15
  - php artisan cek-koneksi
  - php artisan migrate:fresh
  - php artisan storage:link
  - ./vendor/bin/phpunit

- name: publish  
  image: plugins/docker
  pull: if-not-exists
  settings:
    username:
      from_secret: docker_user
    password:
      from_secret: docker_password
    repo: wisnubaldas/flight
    auto_tag: true
    auto_tag_suffix: latest

- name: deploy
  image: appleboy/drone-ssh
  settings:
    host:
      from_secret: server_host
    username:
      from_secret: server_user
    password:
      from_secret: server_password
    port:
      from_secret: server_port
    script:
      - cd docker_app/flight/
      - ls -l
      - docker-compose down
      - docker-compose pull
      - docker-compose up -d
      # - docker exec -it flight_app chmod -R 777 /var/www/storage
      # - docker exec -it flight_app php artisan storage:link
      # - docker exec -it flight_app chmod -R 777 /var/www/public

   
- name: send telegram notification
  image: appleboy/drone-telegram
  when:
      status: [success, failure]
  settings:
    token:
      from_secret: telegram_token
    to:
      from_secret: telegram_id
    message: >
      {{#success build.status}}
      
      ✅ Build #{{build.number}} of `{{repo.name}}` succeeded.

      📝 Commit by {!! commit !!} on `{{commit.branch}}`:

      ```
      {{commit.message}}
      ```

      🌐 {{ build.link }}

      {{else}}
      ❌ Build #{{build.number}} of `{{repo.name}}` failed.

      📝 Commit by {{commit.author}} on `{{commit.branch}}`:

      ```
      {{commit.message}}
      ```

      🌐 {{ build.link }}
      {{/success}}

services:
- name: database
  pull: if-not-exists
  image: mariadb
  environment:
    MYSQL_HOST: database
    MYSQL_DATABASE: test
    MYSQL_ALLOW_EMPTY_PASSWORD: yes
    MYSQL_USER: homestead
    MYSQL_PASSWORD: homestead

