kind: pipeline
type: docker
name: default

steps:
# - name: docker  
#   image: plugins/docker
#   settings:
#     username: ${DOCKER_USERNAME}
#     password: ${DOCKER_PASSWORD}
#     repo: wisnubaldas/cjfi_dev
#     tags: latest
    # dockerfile: Dockerfile

- name: install
  image: wisnubaldas/cjfi_dev
  commands:
  - php -v
  - composer --version

# - name: test
#   image: wisnubaldas/cjfi_dev
#   commands:
#   - vendor/bin/phpunit --configuration phpunit.xml