kind: pipeline
type: docker
name: default

workspace:
  path: /var/www/html/

steps:

- name: build
  image: bitnami/laravel:latest
  pull: if-not-exists
  commands:
  - php --version
  - composer --version
  - composer install
  - php artisan --version
  - cp .env.example .env
  - php artisan key:generate
  - sleep 30
  - php artisan cek-koneksi
  - php artisan migrate:fresh --seed
  - ./vendor/bin/phpunit

- name: publish  
  image: plugins/docker
  pull: if-not-exists
  settings:
    username:
      from_secret: docker_user
    password:
      from_secret: docker_password
    repo: wisnubaldas/flight
    auto_tag: true
    auto_tag_suffix: latest
  
- name: send telegram notification
  image: appleboy/drone-telegram
  when:
      status: [success, failure]
  settings:
    token: 5218343885:AAF7KfKF5DzyrDM_wAKVq1fKHgPi0qZbbm0
    to: 1725917833
    message: >
      {{#success build.status}}
      
      ✅ Build #{{build.number}} of `{{repo.name}}` succeeded.

      📝 Commit by {{commit.author.email}} on `{{commit.branch}}`:

      ```
      {{commit.message}}
      ```

      🌐 {{ build.link }}

      {{else}}
      ❌ Build #{{build.number}} of `{{repo.name}}` failed.

      📝 Commit by {{commit.author}} on `{{commit.branch}}`:

      ```
      {{commit.message}}
      ```

      🌐 {{ build.link }}
      {{/success}}

# - name: test
#   image: wisnubaldas/cjfi_dev
#   commands:
#   - vendor/bin/phpunit --configuration phpunit.xml
services:
- name: database
  pull: if-not-exists
  image: mariadb
  environment:
    MYSQL_HOST: database
    MYSQL_DATABASE: test
    MYSQL_ALLOW_EMPTY_PASSWORD: yes
    MYSQL_USER: homestead
    MYSQL_PASSWORD: homestead

