kind: pipeline
type: docker
name: default

steps:
- name: docker  
  image: plugins/docker
  settings:
    username: ${DOCKER_USER}
    password: ${DOCKER_PASSWORD}
    repo: wisnubaldas/cjfi_dev
    tags:
      - latest
    # dockerfile: Dockerfile

- name: test
  image: wisnubaldas/cjfi_dev
  commands:
  - vendor/bin/phpunit --configuration phpunit.xml