kind: pipeline
type: docker
name: default

# workspace:
#   path: /var/www/html/

steps:
- name: tes-connect
  image: mysql
  commands:
  - apt-get update && install inetutils-ping -y
  - ping database
  - sleep 30
  - mysql -u homestead -phomestead -h database

- name: install
  image: bitnami/laravel:latest
  pull: if-not-exists
  commands:
  - php -v
  - composer --version
  - composer install
  - php artisan --version
  - cp .env.example .env
  - php artisan key:generate
  - php artisan migrate
  - ./vendor/bin/phpunit

- name: send telegram notification
  image: appleboy/drone-telegram
  settings:
    token: 5218343885:AAF7KfKF5DzyrDM_wAKVq1fKHgPi0qZbbm0
    to: cjfi_ci_bot
  
# - name: test
#   image: wisnubaldas/cjfi_dev
#   commands:
#   - vendor/bin/phpunit --configuration phpunit.xml
services:
- name: database
  pull: if-not-exists
  image: mysql
  environment:
    MYSQL_DATABASE: test
    MYSQL_ALLOW_EMPTY_PASSWORD: yes
    MYSQL_USER: homestead
    MYSQL_PASSWORD: homestead

