kind: pipeline
type: docker
name: default

steps:
- name: install
  image: php:7.4.27-fpm
  commands:
  - php -v
  - >
     bash -c "
        apt-get update
        apt-get install wget
      "
  - >
     wget https://raw.githubusercontent.com/composer/getcomposer.org/76a7060ccb93902cd7576b67264ad91c8a2700e2/web/installer -O - -q | php -- --quiet
  # - composer --version
  # - composer install

- name: test
  image: php:7.4.27-fpm
  commands:
  - vendor/bin/phpunit --configuration phpunit.xml