kind: pipeline
type: docker
name: default

steps:
- name: install
  image: composer
  commands:
  - composer install

- name: test
  image: php:7.4.0-fpm-alpine
  commands:
  - vendor/bin/phpunit --configuration phpunit.xml