kind: pipeline
type: docker
name: default



# workspace:
#   path: /var/www/html/

steps:

- name: install
  image: bitnami/laravel:latest
  pull: if-not-exists
  commands:
  - sleep 10
  - php -v
  - composer --version
  - composer install
  - php artisan --version
  - cp .env.example .env
  - php artisan key:generate
  - php artisan cek-koneksi
  # - php artisan migrate
  - ./vendor/bin/phpunit

- name: send telegram notification
  image: appleboy/drone-telegram
  settings:
    token: 5218343885:AAF7KfKF5DzyrDM_wAKVq1fKHgPi0qZbbm0
    to: cjfi_ci_bot
  
# - name: test
#   image: wisnubaldas/cjfi_dev
#   commands:
#   - vendor/bin/phpunit --configuration phpunit.xml
services:
- name: database
  pull: if-not-exists
  image: mysql:5.7.37
  environment:
    MYSQL_HOST: database
    MYSQL_DATABASE: test
    MYSQL_ALLOW_EMPTY_PASSWORD: yes
    MYSQL_USER: homestead
    MYSQL_PASSWORD: homestead

