kind: pipeline
type: docker
name: default

steps:
- name: install
  image: prooph/composer:7.4-zts
  commands:
  # - php -v
  - /bin/bash install.sh
  - composer --version
  - composer install

- name: test
  image: php:7.4.27-fpm
  commands:
  - vendor/bin/phpunit --configuration phpunit.xml